# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://www.your-domain.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Tyrion Lannister # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Witty & Hilarious Rails Developer</h1>
     <p>I'm a kickass developer specializing in Rails, AngularJS, and MongoDB.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: misael.edgar.beltran@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: https://github.com/MisaelB75
  google_plus:
  instagram:
  linkedin:  https://www.linkedin.com/in/misael-edgar-beltr%C3%A1n-81324679/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  https://stackexchange.com/users/12236698/misael-b
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-114529741-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num/"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: date

# BUILD SETTINGS
markdown: kramdown
future: true

sass:
  sass_dir: _sass
  style: :compressed

highlighter: rogue
plugins: [jekyll-paginate]
gems: [jekyll-paginate]
